import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const outifit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: 'AAI Web | %s',
    default: 'AAI Web | Main',
  },
  description: "Generated by create next app",
  keywords: [
    'aai',
    'adamalfarizi',
    "adamalfarizi portofolio",
    "adamalfarizi web",
    
  ]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <html lang="en">
      <body
        className={`${outifit.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
